### ISSUE TITLE
Explanation how to use calendar in Nuxt3

### ISSUE THREAD

**Issue by zwoefler** [fullcalendar/fullcalendar-vue#179]
Explain how to use Fullcalendar-vue with Nuxt3

**Comment by acerix** [comment]
There is an example project for Nuxt v2 here: https://github.com/fullcalendar/fullcalendar-example-projects/blob/master/nuxt/package.json

Does the same not work in v3?

**Comment by zwoefler** [comment]
Unfortunately it doesn't work the same way in Nuxt3, at least when I tried.
My error copying the example:
```
[nuxt] [request error] __vite_ssr_import_1__ is not defined
  at $id_966fc6cf (./.nuxt/dist/server/server.mjs:3642:712)  
  at async __instantiateModule__ (./.nuxt/dist/server/server.mjs:19888:3)
```

If somebody with more experience in Nuxt3 could provide I solution I would be happy.

(I am a Vue-noob)

**Comment by EmilyFlocc** [comment]
@zwoefler did you find a solution to this? or @acerix did you have a chance to take a look?

I'm also having this issue

**Comment by amine-elghazali** [comment]
I have the same problem with nuxt v3 , please help guys ^^'

**Comment by dan-ling** [comment]
I found this very helpful. 
https://stackoverflow.com/questions/71754121/how-to-use-fullcalendar-with-nuxt3-getting-vite-ssr-import-1-is-not-defined

**Comment by r-yongkuk** [comment]
i also have the same problem

**Comment by r-yongkuk** [comment]
Calendar.client.ts

`
<Calendar/>
`

<img width="435" alt="스크린샷 2022-08-10 오후 3 11 04" src="https://user-images.githubusercontent.com/107015574/183828117-bc5db270-8856-4c15-a6c2-35417ce8e248.png">

dayGridPlugin not working after route change

refresh page is ok

**Comment by MilenaPetkanova** [comment]
I just found a solution and posted it [here in StackOverflow](https://stackoverflow.com/a/74614260/4607858). Hope it works for you!

**Comment by zwoefler** [comment]
> I just found a solution and posted it [here in StackOverflow](https://stackoverflow.com/a/74614260/4607858). Hope it works for you!

Will take a look. Running it on the Client only makes sense
